#!/bin/bash

BATS_TAG=v0.4.0
RENV_TAG=Renv

git clone --depth 1 --branch $BATS_TAG https://github.com/sstephenson/bats.git
PATH="$PWD/bats/bin:$PATH"

git clone --depth 1 --branch $RENV_TAG https://github.com/viking/Renv.git
PATH="$PWD/Renv/bin:$PATH"

exec bats ${CI:+--tap} test/"$1"
